#!groovy

// Generated by IBM TransformationAdvisor
// Sun Jan 27 07:06:22 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '--version'
    test='false'
}